### ISSUE TITLE
Unable to get events for security journal using fill event

### ISSUE THREAD

**Issue by patiludayk** [mocircle/jwinlog#4]
for local host or remote host how can we get security journal events using same api provided

**Comment by ruochao** [comment]
Can you try this? https://github.com/mocircle/jwinlog/blob/master/src/test/java/com/mocircle/jwinlog/EventLogManagerTest.java

Generally, you will need to pass the channel name. e.g. Security

**Comment by patiludayk** [comment]
yes, I have tried works for all except "Security" journal

**Comment by ruochao** [comment]
What's your OS, and did you see any exception? What's the behavior?

**Comment by patiludayk** [comment]
OS : Windows 10
Exception : testRetrieveEvents(com.mocircle.jwinlog.EventLogManagerTest)
com.sun.jna.platform.win32.Win32Exception: Access is denied.
(event though I am having admin privileges )

even with admin account I am not able to read/get logs for security journal using this API

**Comment by ruochao** [comment]
Sorry, I don't have win10 environment to reproduce. I need your help to get exception stack. So I can try to analyze. From this exception looks permission issue.

**Comment by patiludayk** [comment]
com.sun.jna.platform.win32.Win32Exception: Access is denied.
	at com.mocircle.jwinlog.api.EventLogApi.getLogInfo(EventLogApi.java:279)
	at com.mocircle.jwinlog.EventLogManagerImpl.getLogInfo(EventLogManagerImpl.java:40)
	at com.mocircle.jwinlog.EventLogManagerTest.tryTestEventParsingAndSize(EventLogManagerTest.java:27)
	at com.mocircle.jwinlog.EventLogManagerTest.testRetrieveEvents(EventLogManagerTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.mocircle.jwinlog.test.WindowsOnlyTestRunner.run(WindowsOnlyTestRunner.java:18)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Comment by patiludayk** [comment]
can we impersonate user to admin while providing session(EVT_HANDLE) to login/EvtSubscribe for localhost. How can we do this using jna

**Comment by ruochao** [comment]
If you use IDE to run unit test, you need to make sure your IDE is run as administrator. I only test that on win7. For now, I've no idea about that without trying on win10. Looks something changed on win10, maybe you can try upgrade the jna version, https://mvnrepository.com/artifact/net.java.dev.jna/jna/5.5.0.

**Comment by patiludayk** [comment]
Hey its all about permission, when I ran same setup with admin privileges. It successfully collects logs from security journal.
Thanks!

**Comment by ruochao** [comment]
Congrats, I gonna close this.
